#Mainteiner Alexandre Rubio (alexrfoliver@gmail.com)
#Create the PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coffee-pv-claim
  labels:
    type: local-path
    app: coffee
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
