#Mainteiner Alexandre Rubio (alexrfoliver@gmail.com)
#Create the PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coffee2-pv-claim
  labels:
    type: default
    app: coffee
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
