apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alexrubiolv/Ghost-app-on-kubernetes.git
    targetRevision: HEAD
    path: ghost-app-acceptance
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: acceptance
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
